name = "RosettaOPFBenchmarks"
uuid = "401b5d79-8d3b-4000-9fa9-f8e7606b98aa"
authors = ["Carleton Coffrin and collaborators"]
version = "0.1.0"

[deps]
ConcreteStructs = "2569d6c7-a4a2-43d3-a901-331e8e4be471"
DataDeps = "124859b0-ceae-595e-8997-d05f6a7a8dfe"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PowerModels = "c36e90e8-916a-50a6-bd94-075b64ef4655"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[weakdeps]
ADNLPModels = "54578032-b7ea-4c30-94aa-7cbd1cce6c9a"
ExaModels = "1037b233-b668-4ce9-9b63-f9f681f55dd2"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
NLPModelsIpopt = "f4238b75-b362-5c4c-b852-0801c9a21d71"
Nonconvex = "01bcebdf-4d21-426d-b5c4-6132c1619978"
NonconvexIpopt = "bf347577-a06d-49ad-a669-8c0e005493b8"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"
OptimizationMOI = "fd9f6733-72f4-499f-8506-86b2bdd0dea1"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[extensions]
RosettaOPFBenchmarksExaModelsExt = ["ExaModels", "NLPModelsIpopt"]
RosettaOPFBenchmarksJuMPExt = ["JuMP", "Ipopt"]
RosettaOPFBenchmarksNLPModelsExt = ["ADNLPModels", "NLPModelsIpopt"]
RosettaOPFBenchmarksNonconvexExt = ["Nonconvex", "NonconvexIpopt"]
RosettaOPFBenchmarksOptimExt = ["Optim"]
RosettaOPFBenchmarksOptimizationExt = ["Optimization", "OptimizationMOI", "ModelingToolkit", "Ipopt"]

[compat]
ADNLPModels = "0.8.4"
DataDeps = "0.7.13"
ExaModels = "0.7"
Ipopt = "1"
JuMP = "1.15"
ModelingToolkit = "9"
NLPModelsIpopt = "0.10"
Nonconvex = "2"
NonconvexIpopt = "0.4"
Optim = "1"
Optimization = "3"
OptimizationMOI = "0.4"
Pkg = "1.10"
PowerModels = "0.21"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["ADNLPModels", "ExaModels", "ForwardDiff", "Ipopt", "JuMP", "ModelingToolkit", "NLPModelsIpopt", "Nonconvex", "NonconvexIpopt", "Optim", "Optimization", "OptimizationMOI", "Test"]
